config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root 'books#index'
  resources :books, only: [:index, :show, :new, :create]
  resources :categories, only: [:index, :show]
  resources :authors, only: [:index, :show, :new, :create]
  post '/ratings/:id' => 'ratings#create', as: 'ratings_create'
  post '/reviews/:id' => 'reviews#create', as: 'reviews_create'
  post '/book_images/:id' => 'book_images#create', as: 'book_images_create'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

    user ||= User.new # guest user (not logged in)
    if user.admin
      can :manage, :all
    else

    end

    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books

  validates :name, presence: true
  validates :surname, presence: true
  validates :agreement, presence: true

  def rating
    result = 0
    count = 0
    self.books.each do |book|
      if book.rating != '' && book.rating != nil && book.rating != 0
        result += book.rating
        count += 1
      end
    end
    return count != 0 ? (result / count).round(1) : 0
  end
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :author_books
  has_many :reviews, dependent: :destroy
  has_many :book_categories
  has_many :authors, through: :author_books
  has_many :categories, through: :book_categories
  has_many :book_images

  paginates_per 20

  validates :title, presence: true
  validates :description, presence: true
  validates :agreement, presence: true

  mount_uploader :image, ImageUploader

  def rating
    result = 0
    count = 0
    Rating.where(book_id: self.id).each do |rating|
      if rating.number != '' && rating.number != nil && rating.number != 0
        result += rating.number
        count += 1
      end
    end
    return count != 0 ? (result / count).round(1) : 0
  end
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  belongs_to :book

  mount_uploader :file, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :book_categories
  has_many :books, through: :book_categories
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/user_image.rb
class UserImage < ApplicationRecord
  belongs_to :user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all.where(favor: true)
  end

  def show
    @author = Author.find(params[:id])
    redirect_to root_path, notice: 'Автор не одобрен' if @author.favor == false
  end

  def new
    redirect_to root_path, notice: 'Не зарегестрированые пользователи не могут добавить автора' unless user_signed_in?
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to root_path, notice: 'Ваша автор находится на модерации и будет добавления после одобрения администратором'
    else
      render :new
    end
  end

  private

  def author_params
    params.require(:author).permit(:name, :surname, :agreement)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:text] != ''
      @books = Book.where("title LIKE ? or description LIKE ?", "%#{params[:text]}%", "%#{params[:text]}%").where(favor: true).page params[:page]
    else
      @books = Book.all.where(favor: true).page params[:page]
    end
  end

  def show
    @book = Book.find(params[:id])
    redirect_to root_path, notice: 'Книга не одобрен' if @book.favor == false
  end

  def new
    redirect_to root_path, notice: 'Не зарегестрированые пользователи не могут добавить книгу' unless user_signed_in?
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to root_path, notice: 'Ваша книга находится на модерации и будет добавления после одобрения администратором'
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :agreement, :image, author_ids: [], category_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    redirect_to root_path, notice: 'Сначало авторизируйтесь!!!' unless user_signed_in?
    Rating.create(user_id: current_user.id, book_id: params[:id], number: params[:number])
    @rating = Book.find(params[:id]).rating
    p '///////////////////////////////'
    p @rating
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    redirect_to root_path, notice: 'Сначало авторизируйтесь!!!' unless user_signed_in?
    Review.create(user_id: current_user.id, book_id: params[:id], text: params[:text])
    @text = params[:text]
    @user = current_user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_images_helper.rb
module BookImagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
    <% if author.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

          <ul>
            <% author.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :author_title %>
    </div>

    <div class="field">
      <%= form.label :surname %>
      <%= form.text_area :surname, id: :author_description %>
    </div>

    <div class="field">
      <%= form.label :agreement %>
      <%= form.check_box :agreement, id: :author_agreement %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Show</th>
  </tr>
  </thead>

  <tbody>
  <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.surname %></td>
        <td><%= link_to 'Show', author %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @author.surname %>
</p>

<br>
<h1>Books</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Show</th>
  </tr>
  </thead>

  <tbody>
  <% @author.books.where(favor: true).each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
    <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
            <% book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :book_title %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, id: :book_description %>
    </div>

    <div class="field">
      <%= form.label :author_ids %>
      <%= form.collection_select :author_ids, Author.all, :id, :name, {}, {multiple: true} %>
    </div>

    <div class="field">
      <%= form.label :category_ids %>
      <%= form.collection_select :category_ids, Category.all, :id, :title, {}, {multiple: true} %>
    </div>

    <div class="field">
      <%= form.file_field :image %>
    </div>

    <div class="field">
      <%= form.label :agreement %>
      <%= form.check_box :agreement, id: :book_agreement %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Show</th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @books %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Show</th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @book.image_url(:thumb) if @book.image? %>
</p>

<p>
  <strong>Categories:</strong>
  <ul>
    <% @book.categories.each do |category| %>
      <li><%= category.title %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Authors:</strong>
  <ul>
    <% @book.authors.each do |author| %>
        <li><%= author.name %>|<%= author.rating %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Rating book:</strong>
  <div id="rating"><%= @book.rating %></div>
</p>

<hr>
<div id="review">
  <strong>Reviews:</strong><br>
  <% @book.reviews.order(created_at: 'desc').each do |review| %>
      <%= review.text %>|<strong><%= review.user.name %></strong><br>
  <% end %>
</div>
<hr>

<div id="photos">
  <% @book.book_images.each do |book_image| %>
    <%= image_tag book_image.file_url(:thumb) if book_image.file? %>
  <% end %>
</div>

<p><strong>Rating review</strong></p>
<%= form_tag "/ratings/#{@book.id}", remote: true do %>
  <%= number_field_tag :number, nil, in: 1...10 %>
  <%= submit_tag 'Add Rating' %>
<% end %>



<p><strong>Review message</strong></p>
<%= form_tag "/reviews/#{@book.id}", remote: true do %>
    <%= text_field_tag :file %>
    <%= submit_tag 'Add Review' %>
<% end %>

<br>
<p><strong>Add new photo</strong></p>
<%= form_tag "/book_images/#{@book.id}", remote: true, :enctype =>"multipart/form-data" do %>
    <%= file_field_tag :file %>
    <br>
    <%= submit_tag 'Add Image' %>
<% end %>
<br>

<%= link_to 'Back', books_path %>

app/views/ratings/create.js.erb
var rating = <%= @rating %>;
$('#rating').html(rating);