config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  root 'books#index'
  resources :books, only: [:index, :show, :new, :create]
  resources :categories, only: [:index, :show]
  resources :authors, only: [:index, :show, :new, :create]
  post '/ratings/:id' => 'ratings#create', as: 'ratings_create'
  post '/reviews/:id' => 'reviews#create', as: 'reviews_create'
  post '/book_images/:id' => 'book_images#create', as: 'book_images_create'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #

    user ||= User.new # guest user (not logged in)
    if user.admin
      can :manage, :all
    else

    end

    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books

  validates :name, presence: true
  validates :surname, presence: true
  validates :agreement, presence: true

  def rating
    result = 0
    count = 0
    self.books.each do |book|
      if book.rating != '' && book.rating != nil && book.rating != 0
        result += book.rating
        count += 1
      end
    end
    return count != 0 ? (result / count).round(1) : 0
  end
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :author_books
  has_many :reviews, dependent: :destroy
  has_many :book_categories
  has_many :authors, through: :author_books
  has_many :categories, through: :book_categories
  has_many :book_images

  paginates_per 20

  validates :title, presence: true
  validates :description, presence: true
  validates :agreement, presence: true

  mount_uploader :image, ImageUploader

  def rating
    result = 0
    count = 0
    Rating.where(book_id: self.id).each do |rating|
      if rating.number != '' && rating.number != nil && rating.number != 0
        result += rating.number
        count += 1
      end
    end
    return count != 0 ? (result / count).round(1) : 0
  end
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/book_image.rb
class BookImage < ApplicationRecord
  belongs_to :book

  mount_uploader :file, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :book_categories
  has_many :books, through: :book_categories
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :books, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/user_image.rb
class UserImage < ApplicationRecord
  belongs_to :user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:text] != ''
      @books = Book.where("title LIKE ? or description LIKE ?", "%#{params[:text]}%", "%#{params[:text]}%").where(favor: true).page params[:page]
    else
      @books = Book.all.where(favor: true).page params[:page]
    end
  end

  def show
    @book = Book.find(params[:id])
    redirect_to root_path, notice: 'Книга не одобрен' if @book.favor == false
  end

  def new
    redirect_to root_path, notice: 'Не зарегестрированые пользователи не могут добавить книгу' unless user_signed_in?
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to root_path, notice: 'Ваша книга находится на модерации и будет добавления после одобрения администратором'
    else
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :agreement, :image, author_ids: [], category_ids: []).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_images_helper.rb
module BookImagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Library</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><a href="#"><%= current_user.name %></a></li>
            <li><%= link_to 'Add book', new_book_path %></li>
            <li><%= link_to 'Add author', new_author_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><a href="<%= user_session_path %>">Sign in</a></li>
            <li><a href="<%= new_user_registration_path %>">Sign up</a></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Разделение <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="<%= categories_path %>">Categories</a></li>
              <li><a href="<%= authors_path %>">Authors</a></li>
            </ul>
          </li>
        </ul>
        <%= form_tag '/books', class: 'navbar-form navbar-left', method: :get do %>
          <div class="form-group"><%= text_field_tag :text, "", class: 'form-control' %></div>
          <%= submit_tag 'Search', class: 'btn btn-default' %>
        <% end  %>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>